[package]
name = "titanv2"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.29", features = ["full"] }
anyhow = "1.0"
futures = "0.3"
log = "0.4"
env_logger = "0.10"

solana-sdk = "=2.1.1"
solana-client = "=2.1.1"

yellowstone-grpc-client = "4.2.1"
yellowstone-grpc-proto = "4.2.1"

tonic = { version = "0.12", features = ["tls", "tls-roots"] }

reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

arc-swap = "1.6"
lazy_static = "1.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

prometheus = "0.13"
warp = "0.3"

tokio-util = "0.7"
bytes = "1.6"

dotenvy = "0.15"
http = "0.2"
bs58 = "0.5"

rkyv = { version = "0.7", features = ["validation"] }

jito-searcher-client = { path = "searcher_client" }
jito-protos = { path = "jito-protos" }


